### ISSUE TITLE
Java 9 Problems

### ISSUE THREAD

**Issue by BijuuKrunos** [OasisArtisan/OasisLight-ServerManager#1]
Hello OasisArtisan,

because of another plugin i had to upgrade to java 9. Unfortunatly i have now problems with the best ServerManager for free over the world :)

`Exception in thread "main" java.lang.ExceptionInInitializerError
        at com.oasisartisan.servermanager.storage.Storage.initStorageTypes(Storage.java:122)
        at com.oasisartisan.servermanager.storage.Storage.loadDataFromFile(Storage.java:61)
        at com.oasisartisan.servermanager.Main.main(Main.java:125)
Caused by: java.lang.NullPointerException
        at java.base/java.io.Reader.<init>(Reader.java:78)
        at java.base/java.io.InputStreamReader.<init>(InputStreamReader.java:72)
        at java.base/java.util.Scanner.<init>(Scanner.java:563)
        at com.oasisartisan.servermanager.Utilities.readLocalFile(Utilities.java:161)
        at com.oasisartisan.servermanager.storage.SQLiteStorage.<clinit>(SQLiteStorage.java:23)
        ... 3 more
`

Thx for Fixing it :)

Greetz Krunos

**Comment by OasisArtisan** [comment]
Thanks for pointing this out.
I will work on it ASAP it should be an easy fix
